export const allPosts = [
  {
    slug: 'ai-lead-scoring-guide-2025',
    cat: 'Lead Generation',
    title: 'The Complete Guide to AI-Powered Lead Scoring in 2025',
    excerpt: 'How modern AI models help B2B sales teams prioritize the right prospects — and how to implement one in your existing stack.',
    read: '8 min',
    date: 'Mar 12, 2025',
    color: '#2563eb',
    featured: true,
    tags: ['AI', 'Lead Scoring', 'Sales Automation', 'Revenue Operations'],
    sections: [
      { type: 'h2', text: 'Why Traditional Lead Scoring Is Broken' },
      { type: 'p', text: 'For years, B2B sales teams relied on rule-based lead scoring: assign points for job title, company size, website visits, and email opens. While better than no scoring at all, this approach had a fatal flaw — it treated all behaviors equally regardless of context, and could not adapt as buyer behavior evolved.' },
      { type: 'p', text: 'The result? Sales teams spending 60–70% of their time on prospects that would never convert, while high-intent buyers slipped through the cracks. Revenue Operations leaders recognized the problem but lacked the tools to fix it at scale.' },
      { type: 'callout', label: 'Key Insight', text: 'Companies using rule-based scoring waste an average of 52% of SDR time on leads that score high on activity but have zero buying intent. AI scoring reduces this waste by up to 60%.' },
      { type: 'h2', text: 'What Makes AI Lead Scoring Different' },
      { type: 'p', text: 'AI-powered lead scoring replaces static rules with dynamic, multi-dimensional models trained on your historical conversion data. Instead of manually assigning weights, the model learns which signals actually predict conversion — and updates continuously as new data comes in.' },
      { type: 'ul', items: [
        'Behavioral pattern recognition — identifies non-obvious action sequences that precede conversion',
        'Firmographic weighting — company-level attributes weighted dynamically based on your actual ICP',
        'Negative scoring signals — learns what disqualifies a lead as readily as what qualifies one',
        'Continuous retraining — as your business evolves, the model adapts without manual recalibration',
      ]},
      { type: 'h2', text: 'The Four Layers of a Modern AI Scoring Model' },
      { type: 'p', text: 'The most effective AI lead scoring implementations combine four distinct data layers. Missing any one of them substantially reduces predictive accuracy.' },
      { type: 'callout', label: 'Layer 1: Firmographic Data', text: 'Company size, industry, revenue, geography, growth signals (hiring trends, funding rounds), and tech stack. This layer establishes baseline ICP fit before any behavioral signals are considered.' },
      { type: 'callout', label: 'Layer 2: Behavioral Signals', text: 'Website activity, content consumption, email engagement depth (scroll depth, time-on-email, link click sequences), and event attendance. Sequence matters as much as individual actions.' },
      { type: 'callout', label: 'Layer 3: Intent Data', text: 'Third-party signals indicating a prospect is actively researching your category — even before they\'ve interacted with you. Providers like Bombora, G2, and Demandbase surface this data.' },
      { type: 'callout', label: 'Layer 4: Relationship Depth', text: 'CRM engagement history, past deal interactions, relationship network (mutual connections, shared customers), and multi-threaded stakeholder engagement within an account.' },
      { type: 'h2', text: 'Implementation Roadmap' },
      { type: 'p', text: 'Rolling out AI lead scoring does not require ripping out your existing stack. Here is a practical four-phase approach most revenue teams can execute in 60–90 days:' },
      { type: 'ol', items: [
        'Data audit (Week 1–2): Assess CRM data quality, identify enrichment gaps, and establish your minimum viable training dataset.',
        'Historical analysis (Week 2–4): Pull 18–24 months of closed/won and closed/lost data. This becomes your training set.',
        'Model training & validation (Week 4–6): Train the initial model, validate against a holdout set, and benchmark against your current conversion rates.',
        'Pilot with one segment (Week 6–10): Deploy to one team or territory. Measure stage conversion rates, not just volume.',
      ]},
      { type: 'h2', text: 'What Results Should You Expect?' },
      { type: 'ul', items: [
        '25–40% increase in MQL-to-SQL conversion rate within 90 days',
        '30–50% reduction in time-to-close for high-scored accounts',
        '15–20% increase in average deal size',
        'Significant reduction in SDR time wasted on low-intent accounts',
      ]},
      { type: 'cta', heading: 'Ready to implement AI lead scoring?', text: 'Our team has helped 500+ B2B companies build and deploy AI scoring models. Let\'s talk about what\'s possible for your pipeline.', btnText: 'Schedule a Free Consultation' },
    ],
  },
  {
    slug: 'marketing-automation-mistakes',
    cat: 'Marketing Automation',
    title: '7 Marketing Automation Mistakes That Are Costing You Revenue',
    excerpt: 'Even well-intentioned workflows can silently sabotage your pipeline. Here are the most common pitfalls and exactly how to fix them.',
    read: '6 min',
    date: 'Feb 28, 2025',
    color: '#7c3aed',
    featured: false,
    tags: ['Marketing Automation', 'Strategy', 'Revenue', 'Workflows'],
    sections: [
      { type: 'h2', text: 'The Hidden Cost of Bad Automation' },
      { type: 'p', text: 'Marketing automation is supposed to save time and increase revenue. But when implemented poorly, it does the opposite — burning through your contact database, damaging brand reputation, and creating a false sense of activity that masks a broken pipeline.' },
      { type: 'p', text: 'We audited 200+ automation setups across B2B companies. Here are the seven mistakes we see most often — and what to do instead.' },
      { type: 'h2', text: 'Mistake 1: Sending Volume Over Relevance' },
      { type: 'p', text: 'The most common mistake is treating automation as a volume game. More emails = more pipeline. This logic is backwards. Irrelevant outreach destroys deliverability, trains contacts to ignore you, and burns goodwill that took years to build.' },
      { type: 'callout', label: 'Fix', text: 'Segment rigorously before you automate anything. Every workflow should have a specific persona, buying stage, and intent signal as its entry criteria. Narrow beats broad every time.' },
      { type: 'h2', text: 'Mistake 2: No Re-engagement Strategy' },
      { type: 'p', text: 'Most teams build lead nurture sequences but have zero plan for disengaged contacts. After 90 days of inactivity, prospects sitting in your CRM are invisible. They do not receive relevant outreach, and sales never touches them.' },
      { type: 'callout', label: 'Fix', text: 'Build a dedicated re-engagement track that triggers after 60–90 days of inactivity. Use pattern interrupts — different subject lines, different content formats, direct value offers. If they still do not engage after the re-engagement sequence, suppress them.' },
      { type: 'h2', text: 'Mistake 3: Ignoring Lead Decay' },
      { type: 'p', text: 'Lead scores are not static. A contact who downloaded your whitepaper 8 months ago and has done nothing since is not a hot lead. Yet most teams never decay scores for inactivity, creating a pipeline full of artificially inflated scores.' },
      { type: 'h2', text: 'Mistake 4: Misaligned Sales-Marketing Handoffs' },
      { type: 'p', text: 'Automation can accelerate MQLs to SQL status — but only if sales and marketing agree on exactly what that means. When handoff criteria are vague, sales ignores MQLs (because quality is inconsistent) and marketing blames sales for not following up.' },
      { type: 'h2', text: 'Mistake 5: Not Testing Subject Lines' },
      { type: 'p', text: 'A 1% improvement in open rate across 10,000 contacts is 100 more conversations. Subject line testing is one of the highest-ROI activities in your entire automation stack — yet fewer than 30% of teams run it systematically.' },
      { type: 'h2', text: 'Mistake 6: Automating a Broken Message' },
      { type: 'p', text: 'Automation scales what you put into it. If your value proposition is unclear or your messaging does not resonate, automation will just deliver a bad experience faster and to more people.' },
      { type: 'h2', text: 'Mistake 7: No Exit Conditions' },
      { type: 'p', text: 'Every workflow needs clear exit conditions. A prospect who books a meeting should immediately leave all nurture sequences. A contact who replies "not interested" should be suppressed globally. Without exit conditions, automation cannibalizes sales conversations in progress.' },
      { type: 'cta', heading: 'Is your automation costing you deals?', text: 'We audit marketing automation setups and identify revenue leaks most teams miss. Book a free 30-minute review.', btnText: 'Book a Free Audit' },
    ],
  },
  {
    slug: 'b2b-email-deliverability',
    cat: 'Email Strategy',
    title: 'B2B Email Deliverability: The 2025 Definitive Checklist',
    excerpt: 'With inbox placement rates declining industry-wide, here\'s exactly what revenue teams must do to ensure their outreach actually reaches decision-makers.',
    read: '10 min',
    date: 'Feb 14, 2025',
    color: '#0891b2',
    featured: false,
    tags: ['Email', 'Deliverability', 'Cold Outreach', 'Infrastructure'],
    sections: [
      { type: 'h2', text: 'The Deliverability Crisis in 2025' },
      { type: 'p', text: 'Google and Microsoft tightened their spam filtering algorithms significantly in late 2024. Average B2B cold email inbox placement rates dropped from 84% to 71% industry-wide. If you are sending from a domain without proper authentication, you are likely landing in spam for the majority of your list.' },
      { type: 'h2', text: 'Part 1: Domain & Infrastructure Setup' },
      { type: 'ul', items: [
        'Use sending subdomains, never your root domain (e.g. mail.yourcompany.com, not yourcompany.com)',
        'Set up SPF records — list all authorized sending IPs',
        'Configure DKIM with a 2048-bit key minimum (4096-bit preferred in 2025)',
        'Enable DMARC with at least p=quarantine — move to p=reject once stable',
        'Register your domain with Google Postmaster Tools and Microsoft SNDS',
        'Warm up new domains for 4–6 weeks before full-volume sends',
      ]},
      { type: 'h2', text: 'Part 2: List Quality' },
      { type: 'p', text: 'Your list is the single biggest driver of deliverability. A clean, verified list from a reputable data provider outperforms a 3x larger unverified list on every metric that matters.' },
      { type: 'ul', items: [
        'Verify every email before sending — use real-time verification (NeverBounce, ZeroBounce, or Debounce)',
        'Remove role-based addresses (info@, sales@, support@) from cold outreach',
        'Suppress hard bounces immediately and permanently',
        'Remove contacts with 3+ soft bounces in 30 days',
        'Maintain a global unsubscribe list across all campaigns',
      ]},
      { type: 'h2', text: 'Part 3: Sending Behavior' },
      { type: 'callout', label: 'Critical Rule', text: 'Never send more than 50 cold emails per inbox per day in 2025. Spread volume across multiple sending domains. Throttle sends throughout the day rather than batching.' },
      { type: 'ul', items: [
        'Randomize send times within defined windows (avoid exactly on-the-hour sends)',
        'Use human-readable From names — "Alex from AIB2B" beats "AIB2B Marketing Team"',
        'Keep text-to-HTML ratio above 60% text',
        'Limit links to 2 maximum per email in cold sequences',
        'Never attach files to cold emails',
        'Include a physical mailing address (CAN-SPAM compliance)',
      ]},
      { type: 'h2', text: 'Part 4: Engagement Signals' },
      { type: 'p', text: 'Modern spam filters do not just look at content — they weight engagement signals heavily. A campaign where 40% of recipients open the email and 10% reply is treated very differently from one where 5% open and nobody replies, even if the content is identical.' },
      { type: 'h2', text: 'Part 5: Monitoring & Recovery' },
      { type: 'ul', items: [
        'Check Google Postmaster Tools domain reputation weekly',
        'Monitor spam complaint rate — above 0.1% triggers action, above 0.3% is critical',
        'Set up automated bounce handling in your ESP',
        'If blacklisted, submit removal requests to MXToolbox-listed providers immediately',
      ]},
      { type: 'cta', heading: 'Is your email infrastructure holding you back?', text: 'We set up and manage complete email deliverability infrastructure for B2B teams. No more landing in spam.', btnText: 'Fix My Deliverability' },
    ],
  },
  {
    slug: 'crm-data-hygiene',
    cat: 'RevOps',
    title: 'CRM Data Hygiene: How Clean Data Unlocks 3x Pipeline Velocity',
    excerpt: 'Dirty CRM data is the silent killer of revenue operations. Here\'s a practical playbook for auditing, cleaning, and maintaining high-quality contact data at scale.',
    read: '7 min',
    date: 'Jan 30, 2025',
    color: '#059669',
    featured: false,
    tags: ['CRM', 'Data Quality', 'RevOps', 'HubSpot', 'Salesforce'],
    sections: [
      { type: 'h2', text: 'The Real Cost of Dirty CRM Data' },
      { type: 'p', text: 'The average CRM degrades at 30% per year. People change jobs, companies merge, email addresses become invalid. After 24 months without active maintenance, over half your database is likely inaccurate.' },
      { type: 'p', text: 'The downstream effects are severe: wasted SDR time on unreachable contacts, inflated lead scores for disqualified accounts, incorrect attribution, and sales forecasts built on phantom pipeline.' },
      { type: 'callout', label: 'Industry Stat', text: 'Gartner estimates poor data quality costs organizations an average of $12.9M per year. For a 50-person sales team, bad data costs roughly 21% of total revenue capacity.' },
      { type: 'h2', text: 'Step 1: The Data Audit' },
      { type: 'p', text: 'Before cleaning anything, you need to know what you are dealing with. Run these four reports in your CRM:' },
      { type: 'ol', items: [
        'Contacts with no activity in 12+ months — likely stale or disengaged',
        'Contacts missing key fields (company, title, email) — incomplete records',
        'Duplicate contacts — same email or same name + company combination',
        'Contacts at churned or closed accounts — should be suppressed from active outreach',
      ]},
      { type: 'h2', text: 'Step 2: Enrichment Priority Framework' },
      { type: 'p', text: 'Not all records are worth enriching. Prioritize based on account score and deal stage. Focus enrichment spend on ICP-fit accounts with active opportunities first, then work backwards through your database tier by tier.' },
      { type: 'h2', text: 'Step 3: Automated Maintenance Workflows' },
      { type: 'p', text: 'One-time cleaning is not enough. You need ongoing workflows that maintain data quality as new records enter the system:' },
      { type: 'ul', items: [
        'Auto-enrich new contacts on creation (connect your CRM to an enrichment provider via Zapier or native integration)',
        'Bounce webhook — when an email bounces, automatically mark the contact and flag for re-enrichment',
        'Job-change detection — use LinkedIn signals to identify when key contacts have changed roles',
        'Quarterly decay review — automatically tag contacts inactive 90+ days for re-engagement or suppression',
      ]},
      { type: 'h2', text: 'The ROI of Clean Data' },
      { type: 'ul', items: [
        'Teams with clean CRM data see 3x higher email deliverability rates',
        'Lead scoring accuracy improves by 40-60% when built on verified data',
        'Sales forecasting accuracy improves significantly when pipeline is based on real contacts at real companies',
        'SDR productivity increases 25-35% when reps stop wasting time on unreachable contacts',
      ]},
      { type: 'cta', heading: 'Struggling with dirty CRM data?', text: 'We run full CRM audits and set up automated enrichment workflows that keep your data clean 24/7.', btnText: 'Get a Free Data Audit' },
    ],
  },
  {
    slug: 'outbound-personalization-at-scale',
    cat: 'Sales',
    title: 'How to Personalize Outbound at Scale Without Sounding Like a Robot',
    excerpt: 'True personalization goes beyond merge tags. Learn the frameworks elite sales teams use to deliver relevant outreach across thousands of prospects without losing the human touch.',
    read: '9 min',
    date: 'Jan 18, 2025',
    color: '#d97706',
    featured: false,
    tags: ['Sales', 'Personalization', 'Cold Email', 'Outbound', 'SDR'],
    sections: [
      { type: 'h2', text: 'Why "Personalized" Outreach Still Falls Flat' },
      { type: 'p', text: 'Most outreach that claims to be "personalized" is just mail merge with extra steps. Hi {First Name}, I noticed you work at {Company} — is not personalization. Prospects see through it immediately, and it actually performs worse than honest, direct outreach because it feels manipulative.' },
      { type: 'p', text: 'True personalization requires demonstrating that you understand the recipient\'s specific situation — their company stage, their role challenges, their competitive landscape, or something that happened to their business recently.' },
      { type: 'h2', text: 'The Three Tiers of Personalization' },
      { type: 'callout', label: 'Tier 1: Account-Level (Scalable)', text: 'Research the company, not the person. Recent funding rounds, new product launches, job postings (signals of growth or pain), earnings reports, press coverage. This level is scalable with the right tools.' },
      { type: 'callout', label: 'Tier 2: Role-Level (Semi-scalable)', text: 'Understand the universal challenges of a VP of Sales vs a Head of Marketing vs a CTO. Build messaging templates for each persona that speak to their specific pain points, metrics they care about, and language they use.' },
      { type: 'callout', label: 'Tier 3: Individual-Level (Manual)', text: 'Reserve for your top 50 target accounts only. Look at their LinkedIn activity, recent posts, conference talks, podcast appearances. This level is not scalable — use it surgically on your highest-value targets.' },
      { type: 'h2', text: 'Building a Scalable Personalization System' },
      { type: 'ol', items: [
        'Define your ICP segments — 3 to 5 is the right number (more than that and you lose focus)',
        'For each segment, identify the 3 most common triggers that indicate buying intent',
        'Build a signal library — a set of sources you check for each trigger type',
        'Write 3 to 5 opening lines per trigger type (not templates — lines that demonstrate understanding)',
        'Automate signal monitoring with Clay, Apollo, or similar tools to surface alerts',
        'Train reps on which opening line to use for which signal — make it a decision tree, not a judgment call',
      ]},
      { type: 'h2', text: 'The First Line Framework' },
      { type: 'p', text: 'Your first line is everything. It needs to signal — immediately — that you did your homework. The best first lines follow one of these four patterns:' },
      { type: 'ul', items: [
        'Recent trigger: "Saw you just announced your Series B — congrats. Teams scaling from 50 to 200 usually hit a specific pipeline problem around this point..."',
        'Shared context: "You spoke at SaaStr last month about moving upmarket. The CRM data challenge you described is exactly the problem we solve..."',
        'Competitive displacement: "Noticed you\'re using [competitor] from your tech stack. Three of their customers came to us this quarter after [specific issue]..."',
        'Role-specific pain: "VP Sales at a 60-person SaaS — you\'re probably managing 3 different spreadsheets to track what your 8 SDRs are actually doing..."',
      ]},
      { type: 'h2', text: 'Measuring Personalization Quality' },
      { type: 'p', text: 'Stop measuring personalization by how "customized" it looks and start measuring by reply rate by trigger type. This tells you which personalization signals actually resonate and which are wasted effort.' },
      { type: 'cta', heading: 'Want us to build your personalization system?', text: 'We create personalization frameworks and automate signal monitoring for B2B sales teams. Book a strategy call.', btnText: 'Build My Personalization System' },
    ],
  },
  {
    slug: 'multi-channel-sequencing',
    cat: 'Sales Automation',
    title: 'Multi-Channel Sequencing: Building Campaigns That Convert in 2025',
    excerpt: 'Email alone is no longer enough. Learn how to build coordinated LinkedIn + email + phone sequences that create the touchpoint density needed to break through to busy decision-makers.',
    read: '11 min',
    date: 'Jan 5, 2025',
    color: '#dc2626',
    featured: false,
    tags: ['Sequencing', 'LinkedIn', 'Cold Email', 'Multi-Channel', 'SDR'],
    sections: [
      { type: 'h2', text: 'Why Single-Channel Sequences Are Dying' },
      { type: 'p', text: 'The average B2B decision-maker receives 120+ emails per day. Open rates for cold email have declined from 24% in 2020 to roughly 16% in 2025. Email-only sequences that worked three years ago now struggle to generate a single reply.' },
      { type: 'p', text: 'But here is what most teams miss: the problem is not email. The problem is single-channel dependency. When you add LinkedIn and phone to the same sequence, response rates increase by 250% compared to email alone. The channels amplify each other.' },
      { type: 'h2', text: 'The Multi-Channel Sequence Framework' },
      { type: 'p', text: 'The most effective sequences follow a specific rhythm across channels. Here is the framework we use for 500+ B2B clients:' },
      { type: 'ol', items: [
        'Day 1: LinkedIn connection request (no note — a note reduces acceptance rates by 40%)',
        'Day 2: Email #1 — short, trigger-based, one clear question',
        'Day 3: LinkedIn message after acceptance — reference the email, add context',
        'Day 5: Email #2 — value-add content (relevant case study or insight, not a sales pitch)',
        'Day 7: Phone call — reference previous touchpoints in voicemail',
        'Day 10: Email #3 — direct ask with social proof ("3 companies like yours...")',
        'Day 14: LinkedIn — comment on their recent post or share relevant content',
        'Day 18: Final email — breakup email with one last direct question',
      ]},
      { type: 'h2', text: 'LinkedIn Best Practices for Sequences' },
      { type: 'ul', items: [
        'Warm up your LinkedIn profile before sequencing — active content presence increases acceptance rates by 30%',
        'Profile views before connection requests improve acceptance rates significantly — trigger a view 24h before sending',
        'Keep LinkedIn messages under 100 words — they are read on mobile',
        'Reference something specific from their profile or recent activity — never generic',
        'Do not pitch in LinkedIn messages — use them for warmth and context, not selling',
      ]},
      { type: 'h2', text: 'Phone in the Sequence: The Forgotten Channel' },
      { type: 'p', text: 'Most SDRs avoid phone because it feels uncomfortable. This is a competitive advantage — if your competitors are not calling, a well-placed call stands out dramatically. The goal of the call in a multi-channel sequence is not to close — it is to humanize the relationship and get a 30-second commitment.' },
      { type: 'callout', label: 'Voicemail Script Formula', text: '"Hey [Name], Alex from AIB2B — I sent you a couple of emails about [specific topic]. Wanted to put a voice to the name. I\'ll keep this short: [one sentence value prop]. I\'ll try you again Thursday, or you can reach me at [number]. Have a good one."' },
      { type: 'h2', text: 'Measuring Multi-Channel Sequence Performance' },
      { type: 'ul', items: [
        'Track reply rate and positive reply rate separately by sequence step',
        'Measure which channel drove the first meaningful response (not just the first touch)',
        'A/B test sequence structure (e.g. email-first vs LinkedIn-first) on a rolling basis',
        'Monitor unsubscribe rate by sequence — above 2% signals irrelevant targeting',
        'Calculate meetings-booked-per-sequence-start, not just open and click rates',
      ]},
      { type: 'h2', text: 'Tools That Power Multi-Channel Sequences' },
      { type: 'p', text: 'You do not need a massive tech stack to run multi-channel sequences. The core tools you need are: a sequencing platform with LinkedIn steps (Outreach, Salesloft, Apollo, or Instantly), a LinkedIn automation layer (Heyreach or Lemlist for LinkedIn steps), and a phone dialer integrated with your sequencer.' },
      { type: 'cta', heading: 'Want us to build your multi-channel sequences?', text: 'We design, write, and launch multi-channel outbound sequences for B2B teams. Most clients are live within 7 days.', btnText: 'Launch My Sequences' },
    ],
  },
]

export function getPost(slug) {
  return allPosts.find(p => p.slug === slug)
}

export function getRelated(slug, count = 3) {
  return allPosts.filter(p => p.slug !== slug).slice(0, count)
}
