export const servicesData = {
  'lead-enrichment': {
    slug: 'lead-enrichment', tag: 'Lead Enrichment', accent: '#1B4FD8', accentLight: '#EEF2FF',
    title: 'Sales Lead Enrichment',
    heroTitle: 'Stop guessing. Start knowing who to call.',
    seoDesc: 'AI-powered B2B lead enrichment that transforms raw contacts into fully qualified prospects with firmographics, intent signals, and predictive fit scores. From $299/mo.',
    desc: 'Transform raw leads into fully qualified prospects with comprehensive data enrichment, real-time intent scoring, and predictive fit models — all before your reps ever touch a record.',
    headline_stat: '40%', headline_label: 'Average increase in qualified pipeline for our clients in the first 90 days',
    features: [
      {title:'Real-time data verification',desc:'Every record is checked against live data sources on enrichment. Stale contacts get updated automatically — no manual refresh needed.'},
      {title:'AI lead scoring',desc:'Our model learns from your historical closed-won data to rank every new lead by their actual probability of converting, not proxy signals.'},
      {title:'Intent data signals',desc:'Third-party intent data from Bombora and G2 surfaces accounts actively researching your category — even before they visit your website.'},
      {title:'Firmographic enrichment',desc:'Company size, revenue, industry, tech stack, growth signals like hiring trends and funding rounds — all appended automatically.'},
      {title:'CRM auto-sync',desc:'Every enriched field writes back to your CRM in real time. Salesforce, HubSpot, Pipedrive, and 40+ others supported out of the box.'},
      {title:'Bulk enrichment',desc:'Upload a CSV or connect directly to your CRM. Enrich thousands of records in minutes without touching a single one manually.'},
    ],
    results: [
      {metric:'40%',label:'More qualified leads',desc:'Average increase in MQL-to-SQL conversion rate within 90 days of going live.'},
      {metric:'60%',label:'Less SDR wasted time',desc:'Reduction in time spent on leads that score high on activity but have zero buying intent.'},
      {metric:'21 days',label:'Faster to first meeting',desc:'Average reduction in time from lead creation to booked meeting for enriched accounts.'},
    ],
  },
  'marketing-automation': {
    slug: 'marketing-automation', tag: 'Marketing Automation', accent: '#7C3AED', accentLight: '#F5F3FF',
    title: 'Marketing Automation',
    heroTitle: 'Build sequences that work while you sleep.',
    seoDesc: 'Multi-channel B2B marketing automation with email, LinkedIn, and phone sequencing. Visual workflow builder, AI-powered optimisation, A/B testing. From $499/mo.',
    desc: 'Build sophisticated multi-channel workflows that nurture prospects automatically. Every step triggers on real buyer behaviour — not arbitrary timers or guesswork about what might work.',
    headline_stat: '250%', headline_label: 'Average increase in total response rates across all channels within 60 days',
    features: [
      {title:'Visual workflow builder',desc:'Drag-and-drop workflow builder that makes complex multi-step sequences easy to build, review, and iterate without writing a line of code.'},
      {title:'Email and LinkedIn sequences',desc:'Build coordinated outreach across email and LinkedIn with message variants, personalisation tokens, and channel-specific timing logic.'},
      {title:'Behavioural trigger campaigns',desc:'Sequences that start, pause, or branch based on what a prospect actually does — not just time delays. Page visits, email clicks, form submissions.'},
      {title:'A/B testing engine',desc:'Test subject lines, message copy, send times, and CTAs at scale. Statistical significance calculated automatically — no spreadsheets required.'},
      {title:'Multi-channel orchestration',desc:'Coordinate email, LinkedIn, phone, and direct mail in a single workflow. Each touchpoint informed by what happened in the last one.'},
      {title:'Deliverability monitoring',desc:'IP warming, domain reputation monitoring, and inbox placement testing built in. Your emails reach the inbox — not the spam folder.'},
    ],
    results: [
      {metric:'250%',label:'More responses',desc:'Average increase in total response rates across all outreach channels within 60 days.'},
      {metric:'3×',label:'More pipeline from same list',desc:'Clients typically generate three times more pipeline from the same contact database after optimising with our automation.'},
      {metric:'40%',label:'Lower cost per meeting',desc:'Average reduction in cost per booked meeting compared to manual outreach processes.'},
    ],
  },
  'campaign-management': {
    slug: 'campaign-management', tag: 'Campaign Management', accent: '#0891B2', accentLight: '#ECFEFF',
    title: 'Campaign Management',
    heroTitle: 'Run campaigns that actually generate revenue.',
    seoDesc: 'End-to-end B2B campaign management with strategy, execution, real-time analytics, and revenue attribution. AI-powered optimisation. From $799/mo.',
    desc: 'End-to-end campaign execution with performance tracking, AI-powered optimisation, and full revenue attribution across every touchpoint — so you always know exactly what is working.',
    headline_stat: '31%', headline_label: 'Average pipeline increase clients see within the first 90 days of campaign management',
    features: [
      {title:'Campaign strategy and copy',desc:'Our team writes the messaging, defines the segments, and builds the targeting — you review, approve, and watch it run.'},
      {title:'Multi-channel execution',desc:'Campaigns run across email, LinkedIn, paid, and direct mail from a single dashboard. Everything coordinated, nothing siloed.'},
      {title:'Real-time performance dashboard',desc:'Live metrics on opens, clicks, replies, meetings booked, and pipeline influenced. Updated every 15 minutes — not daily exports.'},
      {title:'AI-powered optimisation',desc:'The AI continuously tests message variants, adjusts timing, reallocates spend, and surfaces recommendations based on what is actually converting.'},
      {title:'Revenue attribution',desc:'Track every deal back to the campaign, message, and touchpoint that influenced it. Accurate attribution across the full customer journey.'},
      {title:'Weekly performance reviews',desc:'A dedicated campaign strategist reviews performance with you every week, identifies opportunities, and implements changes before the next send.'},
    ],
    results: [
      {metric:'31%',label:'Pipeline increase in 90 days',desc:'Average pipeline growth our clients see within 90 days of launching managed campaigns.'},
      {metric:'4.7×',label:'More meetings per month',desc:'Average increase in qualified meetings booked per month compared to pre-engagement baseline.'},
      {metric:'9×',label:'Average ROI by month 3',desc:'Average return on investment reported by our managed campaign clients by the third month of engagement.'},
    ],
  },
}
